<?
	$headers  = "MIME-Version: 1.0\r\n";
	$headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
	$headers .= "From: Don Traub <dtraub@inkrockit.com>\r\n";
	$headers .= "X-Mailer: PHP/" . phpversion();

       $email = "dtraub@inkrockit.com";
       $fname = "Don";
       $company = "Inkrockit.com";

    $message2 = "<HTML><BODY>";
    $message2 .= "<FONT face='Lucida Grande, Verdana, Helvetica, Arial'><SPAN style='FONT-SIZE: 12px'>";
    $message2 .= "Dear " . $fname . ",<BR><BR>";
    $message2 .= "Thank you for requesting samples from InkRockit. My Name is Don Traub and I will be your personal account manager as well as your Agency liaison (if you need design, mailing or other strategic marketing deployment services.) Consider me " . $company . "’s personal direct marketing concierge.<BR><BR>";
    $message2 .= "In the next several days you should be receiving our sample pack. I’ve attached a picture of the cover so you know what to look out for. Once you’ve got it in your hot little hands, please call me right away at 415.738.6482. I love hearing the spontaneous “oohs” and “ahs” from my customers when they first open our sample pack and I’ll want to discuss the various finishing options that only InkRockit can apply to your piece — finishes that can make the difference between just a good looking print job and a print job that will really produces results for you, your band, your company, or for whatever you’re trying to accomplish. <BR><BR>If you’d like to discuss your specific project with me before your samples arrive, you don’t have to wait. Call me anytime. If I happen to miss your call (I really try not to), just leave me a short message with the best number and time to reach you, and I’ll get back to you as soon as I’m able. Usually that’s before you can eat a small bag of potato chips. :)<BR><BR>Before you get your samples, I wanted to share some important distinctions about InkRockit that give us the edge over almost any other printing company you may be considering.<BR><BR>";
    $message2 .= "<FONT color=#800000><B>For us It’s all about Quality</B></FONT> To begin with:<BR><BR>";
    $message2 .= "<FONT color=#7f0000><B>1. YOUR JOB WILL ALWAYS PRINT PERFECTLY EVEN IF YOUR ARTWORK ISN'T PERFECT!<BR></B></FONT>How can I make that claim? Our art department thoroughly examines your digital files to make sure everything is technically correct. If we discover any problems with your files, we’ll give you a complete report so you can repair the problems and resubmit the files. Or for a small hourly charge, you can have the peace of mind that comes with knowing our award-winning art department will fix the problems for you. Why do we care about your digital files? Because we know that a good print job begins with good artwork. If your pictures have bad color than they'll look bad when we print them. If your die cut, trim marks or fold marks are positioned wrong, then the die cut, trim or fold will be wrong when die cut, trim, or fold it. No matter how good we print it, if your artwork is bad, the printing will look bad. And to the average person, there's no way to distinguish between a bad print job and bad artwork. So we make sure everything looks perfect so you can impress your customers, make more sales, get more distribution and airplay, or accomplish whatever your mission is. And we hope we'll earn your business for life and you'll see us as more as your marketing partner than as just another printer!<BR><BR>";
    $message2 .= "<FONT color=#7f0000><B>2. WE DON'T PRINT YOUR JOB WITH A BUNCH OF OTHER CUSTOMERS’ JOBS.<BR></B></FONT>Your job will run by itself every time. Most of our competition on the web are gang run printers. In case you don't know, a gang run printer runs more than one customer's job at a time. They will collect several customers jobs and print them on the same sheet of paper. <B>When projects are gang run, it’s impossible to deliver accurate color</B> for each piece that’s run together. The result is everyone’s job has some amount of compromise — as much as 20% or more!<BR><BR>";
    $message2 .= "<FONT color=#7f0000><B>3. OUR STANDARD LINE SCREEN IS 240 AND WE GO DIRECTLY FROM COMPUTER FILES TO PRINTING PLATES</B>.<BR></FONT>We are one of only a few companies that offers this quality standard. By combining plates generated directly from your digital files, with an incredible 240 line screen -- not 150-175lpi like most of our competitors – we produce flawless blends (with no banding), and sharp photographs that pop with vibrant color and detail.<BR><BR>";
    $message2 .= "<FONT color=#7f0000><B>4. OUR PRICES ARE DECEPTIVELY LOW.<BR></B></FONT>Deceptive because our prices often compete with gang run printers pricing, so you might think that we somehow cut corners. But as you’ll see from our samples and from everything I’ve mentioned here, nothing could be further from the truth. <BR><BR>";
    $message2 .= "<FONT color=#7f0000><B>5. WE DELIVER FASTER THAN ANYONE IN THE BUSINESS</B>.<BR></FONT>We’re not called InkRockit for nothing. A lot of printers claim to be fast, but after you place your order there turnaround times turn out to be not so impressive. As a spin-off company of IMAGE Team — a highly awarded, two decade old Ad Agency, we understand the importance of deadlines. No matter how good your printing looks, if it arrives one second after your tradeshow or special event, it’s worthless. In fact, when we quote turnaround times, we give you the exact dates you can expect to receive your order — not when it will be ready to ship. And speaking of shipping, your order is double boxed, in 3 ply cartons so that when you open it at your office or special event, it's in the same pristine condition it was when it left our factory.<BR><BR>In closing, I can tell you that I’ve sold printing for other companies before, but I’ve never been more proud to work for a company that is so fanatically devoted to delivering exceptional quality and service. I know if you give me the opportunity to serve you on one project, you’ll never want to go anywhere else again. I hope you will give me that opportunity soon!<BR><BR>";
    $message2 .= "Respectfully yours,<BR></SPAN></FONT><SPAN style='FONT-SIZE: 12px'><FONT face='Verdana, Helvetica, Arial'><BR></FONT><FONT face='Helvetica, Verdana, Arial'><BR></FONT><FONT face=Arial><B>Don Traub<BR></B></FONT></SPAN><FONT face=Arial><FONT color=#bdbdbd><SPAN style='FONT-SIZE: 11px'>-----------------<BR></SPAN></FONT>";
    $message2 .= "<FONT color=#fa6400><FONT size=2><SPAN style='FONT-SIZE: 10px'><B>INKROCKIT</B></SPAN></FONT></FONT><FONT size=2><SPAN style='FONT-SIZE: 10px'><FONT color=#7b7b7b> &nbsp;</FONT></SPAN></FONT><SPAN style='FONT-SIZE: 11px'>| San Francisco | Orlando | Atlanta | Hong Kong<BR>U.S. Sales Office: 205 Springview Dr,, Sanford, FL 32773<BR>800.900.5632 | c: 386.299.3300 | f: 407.842.7965<BR><A href='http://www.inkrockit.com'>http://www.inkrockit.com</A> | http;//www.imageteam.com<BR></SPAN></FONT><FONT face='Lucida Grande, Verdana, Helvetica, Arial'><SPAN style='FONT-SIZE: 12px'><BR><BR>";
    $message2 .= "<img src='http://www.inkrockit.com/images/SAMPLE_PACK.jpg' width='540' height='360'><BR></SPAN></FONT>";
    $message2 .= "</BODY></HTML>";

	   mail($email, "Hi " . $fname . ", welcome to InkRockit!", $message2, $headers);

?>
email sent